name: skillforge
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.1
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
